name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

env:
  CHECK_VERSION: 0.26.0

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-action:
    strategy:
      matrix:
        # Right now macos-13 is amd64 while macos-14 is aarch64 (M1)
        os: [ubuntu-latest, macos-13, macos-14, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          pkl-version: ${{ env.CHECK_VERSION }}

      - name: Confirm download (unix)
        run: pkl --version | grep "Pkl ${{ env.CHECK_VERSION }}"
        if: matrix.os != 'windows-latest'

      - name: Confirm download (windows)
        run: .github/workflows/Check-Version.ps1 "Pkl ${{ env.CHECK_VERSION }}"
        if: matrix.os == 'windows-latest'
